workflows:
   react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_pro
        environment:
            vars:
#                 # Env vars for automatic iOS code signing
#                 # See the following link for more details - https://docs.codemagic.io/code-signing-yaml/signing-ios/
                XCODE_WORKSPACE: "ios/sentry_codemagic_project.xcworkspace" # <-- Put the name of your Xcode workspace here
#                 XCODE_SCHEME: "codemagic_react_native" # <-- Put the name of your Xcode scheme here
#                 # https://appstoreconnect.apple.com/access/api
#                 APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmc3Q0UxYnN0YS1PYjdkblFfemppQkdfR2RTV1FiclpHRVVsdUcwb1R6dkFyRnRWU1RLbFc4Z1BIUURwQUxfZHBiVGpkalAyUzI3OFpqWjdZbi1HUGtzLVZGWlh3dk5tRG1tQ1VMeTNwSXFKT0ZWOVY2amNvdDRLTEQ0Nmh2UU9NM19xbEI=) # <-- Put your App Store Connect Issuer Id here
#                 APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmc3Q0QyNG1Jd1c4TFl5ZVVyNmFoZHVVbFFKZzVmNm1PTjlYZE1ab3dIYkx1MWJzcnkzRlVSalhwVXNpSHZUdW9jQ3o2TkhXdW5WUVZNd1V2bzZtOWZzZmpmdWc9PQ==) # <-- Put your App Store Connect Key Identifier here
#                 APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmc3Q0VicVpVMDV1QWt0M1YxLTJCUXRublN4bC1MTlhoUnoxZnZ0ODkwUk0wNkJtVDB2UGgxWEtHRGU0ODRYeDBuTHkyVVNQeGpqVUxpekRZelZUamhiYkNrTEFsM2Q3SnJDMEJQNWdDTk5VVXgyaUROVXBnMWVPY1MxUk1GTUNZTTNCRERLTlFtT29Lb0UtQ0FEOERIWU5fZWdrTm5JS1N6RnlMenRzdE00Z2w3aWtNdkU5Qnd0SmlNWlp5ZGlkVG1MNXFObGlSNEFHMnVIRU9KUjY1d0tyYmtTdW9rSjNBLUJoX0tzWVgwdmZCYkZCN2g1NzBFemtfS0ZDeE9vMlB2ZU95MlItWXRoQzdEOTdFcTU3ZXhFb1pacERiNUVSOWhDN2QwMkhHOFFJSVNiTmFXUm5hR1RldzNsT0RUOXVLZFVRcTEzUFpsSW5UcVB4dnhIMlotLTZGRFVyMTI3ZHRabVFhZGJoQzJRLXRrNmFfSUI2RDBTV1ZHcHk5bURmblhNZHpOUnVTVnhBY1JsNnRGb3lXdUdjU1Y5Z3F2VFBBcGtxNjhxRUFfYmVnVEFYWT0=) # <-- Put your App Store Connect Private Key here
# #                 CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhKa3NKZXE0Z0JFTzRnS245RzFxNHFVQ2N6ZkhiVjI4UWZqOW44dkRVRy1uOWtUUkl6czVVLTkwYXZDZ21tdEh0NVU0NVdRMzdBTkY4NWtidU9KYTdXSm4yLWJ6cTZYVmRhLS1DMUNYeGJ3NHc4VjVnT2g5VVR4VURlUkRFdlZsY0V3b2RiOXJZOW52UEtac3JLbVFtY0ZiOTBPYUVQRE4yZXpQcTNkbEhuY2UtNHkteE5SX1V4dnNGYzVMdVBRNkU1NTAyZ2dRM2NCdW1CczhrbTd6N3FsamdwOHBKWUYtZDd6akFoTHRjQVBWTFRxbFhaUnJKWWtnVVRfSHVaWGduOHZNaHVpaDZTOVFfSnRSMm5qZ2xLNFFwY2d5ZnhPbHU0eTFfaERSWk5zUlVVcWZ3OHFxYlhfSGlTZThMSDIyS1djMTdmdWdraHlSbjZFWUoxbUd6Nm1oNHpwc1hYMDFNV0tuYndZc1dERzNJSmxmU0xncWdySFl0Ul84dG0taFZzSXU1S0JGcnBqUHNPQlJiemhMTkZWTUI0S0Y0OHNTR2MtVWJzNkNMT1FTU19jaU0zV19hcUF5ekJMb3Vxenl3cHBuRk9uZWtQbzZUbFhrSnNaUHM1ZzNjRENQdWRDQTgyOG9zUXg4U0NXNXNSQmduMjZkbnF3N0FNTmVsdGx2d1JiQjladFUxc3h6TjJLV1NJMGVPQ1NCSXRBX2xNVDB2UGZETUYxdUpQaWZUWWl3OHZiR1loQ0tFZHBrWTh4Y3pMMFhEaU9Qa21paEdSMGJnVUJRQVYzMl90cmNIeDB6UUcwdGFNOVlvVUJfeXU1SGJXZEtGeEdHTnVyTWM1b192N2FDRWNobU5BWGxpdmk5dDFYZ01NT1NqSnczbEJZc05LN2NCaHN3Q09McUY5T090OUVzZFdCaUhJdkxObVFqYnRXaE9LT090Sk54VDFUb0NvNW1ycE0tY2I0eURydzhCTThIUmxkRjFaeUlVbDJFbFJocy1PYU9yQ2Y0b1owVmJJZXpmdEFCcUQweXJWd2dtN3hXVzBWNGUzMjhJaFhBQ255UDAtUk5HUW5KTlN4Y2cwckdFRVV3UUMzLXhrcnp4R0NwSTFIRUwxeWw0Si1TX0FvZWZVNTFsc0U1RmhKaDhFc2MwWUVmQ3RtQXFfVEh6cXZlNnRvVXBfX1dzdHBRMVhQOGlJajNfYlN2eHhOcnNFT3A2cEsxRzhiRFF6eW9WZHYtcVdNTlg0M2lqSmdWZU83ZWNpb3ZVV2FUYk0ycUwydGZYai1iNkJOMDZveEU5SUJaNWZzaHM5WFBxR0diLXN3N1NiX0ZJZDlwM2FwVlNCaEV2eWx0bHVkamdQS3pZMzBzS0hxMlpMdjJZMEo5OWR3TU92Nk42VHdWQWN0UWR6U3Ezb0haTGZ3MnlxTlhxVEphTnltVm9vcExPMF9nZjhsTUVhTkZwY19Od0tLNDE2ZE94ZXlNbG5RWGYzWmpWZE9sWTk4a0dkYkM3OC00X0h4YkdDeXU4eWlIX1h6ZFM4Nm95aTU0a3BXQi1BUXNkNjJVdnhsMFZFODFya3dWZjkyNjRtdWRoUEZ5YlFfaVNiWDBXMWR5eldXRFpILTR0Nl9OWWpkM0VDNWJsVjcyM1Q5U0MwbVhya1RDY2JCYU95ZGszMmlHVHh5Vzd6MVUtZzRGQ2w0UTltSWx4MVVadE04dTg4VkFNWXEyV0Ixeldua0w5QTA1eFJtbF9IWmZFOXV1d0phTDNtSUpVOTRqN2N5cS16dWMtMHprc3pTVHlUeFhRS1d1MnhHTmFLazd2WmRZWXZQb0ZMNXBpYUwzVTd4a3RfYjZ4RUptUDc0eWNhN2Zrc25GQlZFcktVM3Z4TXNfcDlUdnFhYU5WQ3hKZU91OGNJQThRQkpEcWRKdm5ybENrUUE2ZzM5c2oxWWczQmNjSGRCR24wanJxWXBMTlJCZlZfRWJlcFdmVFFmaEZPVnY1ZkdjMmMxdjA1V3dadXNTZEZid0stank0N0d1SzB3ZTk1QnNyb3c3UUFlbF9oVVFDaWNab1Q3ZlRSVW9ER3hhc29ZU0ZkQXFWOGZKMlNITE1uNWpYM2Zxd0tmTkxiTFIxNWlxejFFc2lsNmxGTE1WeDlxM2E1bE9yWHlIZTE5WHhzYnlFWEpURVRrVHpoSUFaMzhsU3pmRW5vd2Z0SFZhWVJQNW5JR2dTNkpzYUlGU21LSmRzZ1RtV3prSVBYM2hOb3hkQWpWQ0NZcURnbnpZM3piS0Z1SnNONWgwdTZJdW93TXFPMGh5WHJPSGZzcHJxaWdob041Qk12Z3BuSXJKZGE5dE15VEN5MkJSaV9JSUIwRjRPbndNd3F0djVJcVFOODAtV2ZnVi1zYVAtSkk1NkdVVEUzS0t0aUozY1E2NlBaZkN5WjZlM3dUTFJnLXVjQlUzUWNPbjJSeE1rdjBZcG1hZnlmdEdmX2xRRmRweVd5ZTRQUkg3dUNSMG03VWk3ZWNPR002cDJQd2h1UE4zU0RVYmlzNTZJZjJYVVptaE5nYTJ1UXFwMXpyNVJfdmxtNG5idVphMkpEekptazJOUk04U0Vrb1NubUlCeW9ub3JfNHRlSmFwQlFNRFRGQVp5YjVWSXczY0JQSEw3Z0xCSkJKQllpRWJ3YldCY2poYXNUWFMwZUdzTF80c0t4dS1HaDl6QmxMTjB0clQ5Ump4Wmp4bjFaN0NSVGZ2VWdRR21mbDQxUDFyQnE4WDN4TzQ3Ry1LLWp1cE54QXJGRWYwZ2NuS2ZCVWZjejY2VmYyaTBxbUlGVmFQc2VQY00zUUpKN0lnZGh0azh3NlNxdkFwSWFxZUpqQ1lmdXN1YlBYb3dXejlSMGlPcC0tQUdDeTBEOEhzdDJzVEl2LWdGLWgtdnRLakxEV1lZN1RxSGpEd2lxbVY1QUdrZ3l6VDhFZHJ4d21NOTJYLUs2SkNhZUVUUkU5bWhhQkc3MW1pQTRLb2VtRFFhTThKTHptNEE5bXNFYW8zS0t5Ym0zNDdldE9mZHRuTGw4YnZNb3BzWDFzblBwdFhaZG5XekoteWdVWXN4TmJLLUVnTU5ySWFuQy0ybzl0WVFHdz09) # <-- Put your Certificate Private key here
                BUNDLE_ID: org.reactjs.native.example # <-- Put your Bundle Id here e.g com.domain.myapp
                XCODE_PROJECT: "ios/sentry_codemagic_project"
           
            node: v16.11.1
            xcode: 13.0
            cocoapods: default
            groups:
               - ios
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
#             npm install --save @sentry/react-native
#             npx @sentry/wizard -i reactNative -p ios
            - name: Install CocoaPods dependencies
              script: |      
                cd ios 
                pod install
            - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
              script: |
                keychain initialize
            - name: Increment build number
              script: |
                #!/bin/sh
                set -e
                set -x
                cd $FCI_BUILD_DIR/ios
                # agvtool new-version -all $(($BUILD_NUMBER + 1))
                agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
            - name: Fetch signing files
              script: |
                # For information about Codemagic CLI commands visit: https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/README.md
                # For details about the --type paramater below - https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/fetch-signing-files.md#--typeios_app_adhoc--ios_app_development--ios_app_inhouse--ios_app_store--mac_app_development--mac_app_direct--mac_app_store--mac_catalyst_app_development--mac_catalyst_app_direct--mac_catalyst_app_store--tvos_app_adhoc--tvos_app_development--tvos_app_inhouse--tvos_app_store
                app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_ADHOC  --create
            - name: Use system default keychain
              script: |
                keychain add-certificates
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles  --project="ios/codemagic_react_native.xcodeproj"
            - name: Build ipa for distribution
              script: |
                xcode-project build-ipa --workspace "$XCODE_WORKSPACE"  --scheme "$XCODE_SCHEM" 
#             - name: Build .app
#               script: |
#                  xcodebuild build -workspace "ios/$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#             - name: App upload and Set app id in environment variable
#               script: |      
                
#                 APP_URL=$(curl -u "nihalagazade_JxPH1i:4y5LkQnzzGkv2s7ERZ4q" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@build/ios/ipa/codemagic_react_native.ipa" | jq -r '.app_url') 
#                  echo $APP_URL
#                 RESPONSE=$(curl -u "nihalagazade_JxPH1i:4y5LkQnzzGkv2s7ERZ4q" -X POST "https://api-cloud.browserstack.com/app-automate/xcuitest/test-suite" -F "file=@Users/builder/codemagic_react_native_42_artifacts.zip")
#                  echo $RESPONSE
#                 TEST_URL=$(echo $RESPONSE | jq -r '.test_url')
#                  echo $TEST_URL
#                 curl -X POST "https://api-cloud.browserstack.com/app-automate/xcuitest/build" -d "{\"devices\": [\"iPhone 11 Pro-13\"], "app": ""'"$APP_URL"'"", \"deviceLogs\" : \"true\", "testSuite": "'"$TEST_URL"'"}" -H "Content-Type: application/json" -u "nihalagazade_JxPH1i:4y5LkQnzzGkv2s7ERZ4q"    
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
           scripts:
             - name: Sentry
               script: |      
                  echo "Find build artifacts"
                  dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/sentry_codemagic_project.xcarchive/dSYMs -name "*.dSYM" | head -1)
                  if [[ -z ${dsymPath} ]]
                  then
                    echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
                  else
                    echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
                    sentry-cli --auth-token 13beeb2899ca4e80b545cb4a8dae56b889a19cacf6834b6f8c5540987aedd4f5 upload-dif --org nevercode-24 --project react-native $dsymPath
                  fi